### ISSUE TITLE
aws_config.rb does not support cn-north-1 region 

### ISSUE THREAD

**Issue by psu1025** [logstash-plugins/logstash-mixin-aws#11]
Logstash s3 plugin (aws_config.rb) does not support "cn-north-1" region.

config :region, :validate => [US_EAST_1, "us-west-1", "us-west-2", "eu-central-1",
"eu-west-1", "ap-southeast-1", "ap-southeast-2",
"ap-northeast-1", "sa-east-1", "us-gov-west-1"], :default => US_EAST_1

please add china region.

best regards.

**Comment by ph** [comment]
Done in latest version of the gem
