### ISSUE TITLE
Instructions: How to use with multiple credentials

### ISSUE THREAD

**Issue by cdenneen** [logstash-plugins/logstash-mixin-aws#14]
Can someone tell me in order to move away from the deprecated credentials parameter in individual inputs in favor of this... how you can specify many different credentials?

So let's say you have multiple IAM profiles or even multiple amazon accounts and you need to read from resources in all of them S3, SQS, SNS, etc. You'll need to be able to setup multiple credentials and then be able to reference the appropriate one in the input/output.

**Comment by andrewvc** [comment]
@cdenneen plugins using this mixin accept common parameters `access_key_id`, `secret_access_key`, `session_token`, and `proxy_uri`, and `aws_credentials_file`. Does that help @cdenneen ?

**Comment by andrewvc** [comment]
@cdenneen You can see all the parameters here: https://github.com/logstash-plugins/logstash-mixin-aws/blob/master/lib/logstash/plugin_mixins/aws_config/generic.rb

**Comment by cdenneen** [comment]
@andrewvc my question is this:

let's say you have 3 AWS accounts (or just 3 different IAM roles).
you specify 3 s3 inputs and maybe 3 sqs inputs.
In the old input you could specify creds per input but now using mixin-aws how do you specify which creds go with which input/output?


input1 s3 = role input1s3
input2 sqs = role input2sqs
input3 s3 = role input3s3sqs
input4 s3 = role input3s3sqs
input5 sqs = role input5sqs
input6 sqs = role input5sqs

**Comment by andrewvc** [comment]
@cdenneen it works exactly the same way. The mixin is used by the plugin internally to de-duplicate the auth logic. Does that make sense? You can still specify parameters separately per input. The mixin is just an implementation detail.

**Comment by cdenneen** [comment]
@andrewvc okay got it... the credentials deprecated warning is what was confusing me. So the credentials parameter was replaced with access_key_id, secret_access_key, or aws_credentials_file

**Comment by andrewvc** [comment]
@cdenneen yep!
