### ISSUE TITLE
invalid configuration option `:proxy_uri' with AWS Ruby SDK V2

### ISSUE THREAD

**Issue by wanghq** [logstash-plugins/logstash-mixin-aws#15]
In AWS Ruby SDK V2, the proxy_uri option is changed to http_proxy.

http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#initialize-instance_method
https://forums.aws.amazon.com/thread.jspa?threadID=172034

Using the proxy_uri will cause **ArgumentError: invalid configuration option `:proxy_uri'**
https://github.com/logstash-plugins/logstash-mixin-aws/blob/master/lib/logstash/plugin_mixins/aws_config/v2.rb#L20

A fix would be just changing:
```ruby
    opts[:proxy_uri] = @proxy_uri if @proxy_uri
```
to:
```ruby
    opts[:http_proxy] = @proxy_uri if @proxy_uri
```

**Comment by andrewvc** [comment]
Released with v1.0.1 of this plugin. Thanks for finding this @wanghq!
