### ISSUE TITLE
Update aws-sdk to 2.3

### ISSUE THREAD

**Issue by lukewaite** [logstash-plugins/logstash-mixin-aws#24]
The aws-sdk gem is currently locked at `~> 2.1.0`. Though it was originally locked to `~> 2`, it was updated to it's current lock in 8a3463dba7d8b116e92fec7b44f0011afd52a551. I'm not sure if that was for a particular reason I'm missing, or just to be safe.

2.3.22 was [released yesterday](https://github.com/aws/aws-sdk-ruby/releases/tag/v2.3.22) which (among other things) includes the support for the ability to assign an AWS IAM role directly to a task. 

Is there any chance that we could update the lock to allow minor version updates, or update the minor to `2.3`? I have forked, bumped, and [let travis run](https://travis-ci.org/lukewaite/logstash-mixin-aws/builds/144879530) against `~> 2.3.0` and it does pass. I've not opened a PR as of now as I see you typically bump the version in a single commit and I'm unsure whether this would qualify as a patch or minor release according to the standards on this project.

Please advise if you're open to a PR with this change.

If we could get support for this in, it would be beneficial to our workflow, and I'm sure to others as well.

**Comment by suyograo** [comment]
@lukewaite we are definitely open to a PR! Thanks for contributing to Logstash! You can make the constraint:

`s.add_runtime_dependency 'aws-sdk', '~> 2.3.0'`

**Comment by suyograo** [comment]
@lukewaite we can do a minor version bump since this brings in new features.
