### ISSUE TITLE
assume_role not using access_key_id and secret_access_key

### ISSUE THREAD

**Issue by jayjmin** [logstash-plugins/logstash-mixin-aws#44]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: latest
- Config File (if you have sensitive info, please remove it):
input {
  s3 {
    "access_key_id" => "ACCESS_KEY"
    "secret_access_key" => "SECRET_KEY"
    "role_arn" => "arn:aws:iam::111111:role/RoleToAccessS3"
    "role_session_name" => "SessionName"
    ... (trunc) ...
  }
}
- Steps to Reproduce:

When we give both role_arn and access_key_id & secret_access_key pair, it only use access_key_id & secret_access_key pair to do basic authentication, and does not assume role with the role_arn.

This is necessary if Logstash is not running on EC2, which needs basic authentication with access_key_id & secret_access_key in order to assume role. 

This is because once access_key_id & secret_access_key pair is given, credentials function just returns new credential using only these two values. It does not care of role_arn.
 
https://github.com/logstash-plugins/logstash-mixin-aws/blob/cd7d370b578c08025a8dbfb3c806fd6247961e31/lib/logstash/plugin_mixins/aws_config/v2.rb#L40

We can add one more case here to return credential after assume role if all three fields (access_key_id & secret_access_key & role_arn) are given. It will be something like:

                   if @access_key_id && @secret_access_key && @role_arn
                     assume_role_with_cred
...
...
...
    def assume_role_with_cred
      Aws::AssumeRoleCredentials.new(
        :client => Aws::STS::Client.new(:region => @region, :access_key_id => @access_key_id, :secret_access_key => @secret_access_key.value),
        :role_arn => @role_arn,
        :role_session_name => @role_session_name
      )
    end

**Comment by cabberley** [comment]
@jayjmin I have made a branch which will suit your needs, However your scenario will work without this change, The AWS SDK will actually try do this

_Default credentials are loaded automatically from the following locations:
ENV['AWS_ACCESS_KEY_ID'] and ENV['AWS_SECRET_ACCESS_KEY']
Aws.config[:credentials]
The shared credentials ini file at ~/.aws/credentials (more information)
From an instance profile when running on EC2_

AS stated in the SDK [https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/STS/Client.html](url)

So if you install for example AWS CLI and store credentials using `AWS Configure` the Logstash plugin will use those for assume role.
