### ISSUE TITLE
Update AWS gem from v1 to v2.

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-mixin-aws#8]
The current plugins *sqs and the *s3 plugins are using api v1, Amazon have released a 2.0 of their libraries and did a few changes that could potentially breaks the plugins we will need to update the plugin sto use the new version since they are only doing bugfixes in v1. ref #7

**Comment by dwagner2301** [comment]
I converted the output-sqs-plugin to the v2 api just to start the transition to the v2-sdk and to see where the whole process is going. I'm planing to update the input-sqs plugin pretty soon as well. 

You can find my changes for logstash-mixin-aws under: dwagner2301/logstash-mixin-aws@e542036e19e29abf48c2a6e51db1f97cb232ad61
and the changes the logstash-outpu-sqs repo here: dwagner2301/logstash-output-sqs@bd25307de6d3d5237bf10ef217c29c8d1682082f

@ph what do you think about the changes? Does it look like it's going in the right direction? If not, what should be done differently?

**Comment by dwagner2301** [comment]
Just finished moving the logstash-input-sqs plugin to the v2-sdk. I was able to test the whole chain stdin->SQS-Output->SQS-Iinput->stdout with success.

Please take a look at dwagner2301/logstash-input-sqs@c0c7cc1369d1759dee8a1d39dee580e27e2e3957 ,let me know if I'm on the right track, tell me your opinion about the changes and what you thing should be done next.

**Comment by dwagner2301** [comment]
@ph did you have any chance to take a look at the changes?

**Comment by wanghq** [comment]
+1 for this. Seems some new services are not supported by v2 SDK. @ph, could you at least use aws-sdk-v1 to load AWS ruby SDK, so it's possible to use v2 for any plugin? Thanks!

http://docs.aws.amazon.com/AWSRubySDK/latest/index.html

**Comment by ph** [comment]
@dwagner2301 I've created a PR for the mixin #13, its a bit different from your implementation.
I needed to make sure it's backward compatible with v1 option in the plugins, so I couldn't remove the `use_ssl`

**Comment by ph** [comment]
@dwagner2301 Would you mind testing your PR with the #13?

**Comment by ph** [comment]
@dwagner2301 I've looked at your initial commits for sqs input and output look great to me, would you mind creating PRs for both of them. You can remove the `aws_service_endpoint` method in both of the plugin since the V2 module will provide it by default and you can remove the dependencies in the gemspec.

**Comment by ph** [comment]
@wanghq should be merged and released shortly.

**Comment by wanghq** [comment]
Thanks @ph !

**Comment by ph** [comment]
@dwagner2301 Can you make an actual pull request with your changes with the SQS plugin and make sure the CLA is signed I will help for writing the tests.

**Comment by dwagner2301** [comment]
@ph sorry for replying so late (I must have missed the notifications...)! I'm going to create a pull request with the changes in the next couple of days if that's fine with you.

**Comment by ph** [comment]
Awesome, @dwagner2301 I'll help to add more test to it, I just want to make you have credits for your work.
